---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Sepideh AhmadiTalei"
date: "September 18, 2023"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:

```{r load-pkg-data}
#| message: false
# install the package 'Lahman'
install.packages('Lahman')
# load the package
library(Lahman)
```

## Exercises

### Exercise 1

```{r}
dim(Teams)
```

```{r glimpse-data}
dplyr::glimpse(Teams |> head())
```

The `Teams` dataset has \_*3015*\_ observations and \_*48*\_ variables.

### Exercise 2

```{r team W/L record during years 2004-2012}
mets <- Teams  %>% 
  dplyr::filter(teamID == "NYN")
my_mets <- mets %>% 
  dplyr::filter(yearID %in% 2004:2012) %>%
  dplyr::select(yearID,G,W,L)
my_mets
```

### Exercise 3

```{r}
mets_ben <- Teams |>
  dplyr::select(yearID, teamID, G, W, L, RA, R) |>
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)
mets_ben
```

```{r renaming variable}
mets_ben <- mets_ben |>
  dplyr::rename(RS = R)    # new name = old name
mets_ben
```

### Exercise 4

...

### Exercise 5

...

### Exercise 6

...

### Exercise 7

...

### Exercise 8

...

### Exercise 9

...

### Exercise 10

...
